### ISSUE TITLE
Existing port binding is not always respected when choosing a local port.

### ISSUE THREAD

**Issue by i8r** [zalando-stups/zign#38]
How to reproduce:
On Mac, start a docker image that is bound to port 8081, e.g. `docker run -p 8081:5000 training/webapp python app.py` (I used Docker version 1.12.3).
Then run `python3 -m zign` and it will use port `8081` but Chrome (and Safari) resolves `http://localhost:8081` to the docker image.

It seems to be related to ipv4 and ipv6 since `http://[::1]:8081` goes to the docker image while `http://127.0.0.1:8081` goes to server spawned by zign.

**Comment by hjacobs** [comment]
Thanks for reporting this issue. Idea: we could check with a single request whether localhost:8081 really goes to our server before opening the browser.

**Comment by pmeinhardt** [comment]
Hey, we just spent time on figuring out why `zign` wouldn't work for us. We were always redirected to a server running locally which obviously did not know what to do with this redirect and zign could never completed the action. We read through the zign source code to figure it out.

We only found this issue afterwards 🤦‍♂ 

Since ports `8080`, `8081` are not that uncommon in web projects, it'd be great for zign to detect whether a port is already in use (and to definitely not fail silently when starting its redirect server on that port).

My suggestion would be to:

1. Make sure to that the redirect server raises an error if its port is already taken.
2. Add code to try and bind to a port first and if it is already in use (errors), try until a free port is found.

Cheers

**Comment by hjacobs** [comment]
@pmeinhardt do you want to do a PR?

**Comment by pmeinhardt** [comment]
I'll give it a shot ✌️

**Comment by pmeinhardt** [comment]
Mmh. Actually, on second look, it seems like there's already some code in place to try and mitigate this issue. But it seems it's not working correctly (or we somehow ended up with an outdated version of zign in the tools that we're using).

https://github.com/zalando-stups/zign/blob/1016b1a7867e48c671bfe70fe9e7ce26b96107ea/zign/api.py#L151-L167

I'll take a closer look and will post an update.

**Comment by pmeinhardt** [comment]
Update: We're using the most recent version. However, I've found that the code – as it is written right now - will not work. Instantiating an `http.server.HTTPServer` instance with a port that is in use will not raise a `socket.error`.

A simple option could be to just pass a `port_number` of `0` and let the server choose a port automatically, as per the example in the [`socketserver` docs](https://docs.python.org/3.5/library/socketserver.html#asynchronous-mixins)

![image](https://user-images.githubusercontent.com/706519/63685422-c2737080-c7ee-11e9-8e43-8506a6cfa2b5.png)

**Comment by mikkeloscar** [comment]
You can't choose a random port as this port has to be configured as part of the url on the Oauth2 provider side for the whole flow to work. So it can only be one of the "approved" ports.

**Comment by pmeinhardt** [comment]
🤔 Couldn't you approve more ports? What's the reasoning behind allowing `8081` to `8181`, but not others?

**Comment by pmeinhardt** [comment]
But okay, if that's the case, then it should at least raise an exception ✌️
